all: movies sherlock

movies:
	mkdir movies
	curl -o movies/input.txt http://ad-teaching.informatik.uni-freiburg.de/InformationRetrievalWS1617/movies.txt

sherlock:
	mkdir sherlock
	curl -o sherlock/input.txt https://sherlock-holm.es/stories/plain-text/cnus.txt
